### ISSUE TITLE
POM file is missing scala-library depedency

### ISSUE THREAD

**Issue by olafurpg** [com-lihaoyi/geny#32]
The geny POM file is missing a dependency on scala-library https://repo1.maven.org/maven2/com/lihaoyi/geny_2.13/0.6.9/geny_2.13-0.6.9.pom

This missing dependency causes compilation to fail if you try to compile the sources inside https://repo1.maven.org/maven2/com/lihaoyi/geny_2.13/0.6.9/geny_2.13-0.6.9-sources.jar

A workaround is to manually add scala-library.jar to classpath, but it would be nice to avoid this workaround. Feel free to close.

**Comment by lolgab** [comment]
It might actually be a bug with Mill not adding this dependency and everything works because it is added either way by sbt, other dependencies or someone else. I will take a look to see if I can find the cause. Thanks for reporting @olafurpg

**Comment by olafurpg** [comment]
@lolgab Thank you for opening the issue in the Mill repo! I agree this is most likely a Mill issue, not Geny-specific.
